Sistema/Troquelcart/Troquelcart/urls.py
from django.contrib import admin
from django.urls import path, include
from pegado.views import home_view

urlpatterns = [
    path('', home_view, name="home"), 
    path('admin/', admin.site.urls, name="admin"), 
    
    #Incluye la configuracion de URL de pegado
    path('pegado/',include ('pegado.urls'))
]

Sistema/Troquelcart/pegado/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    home_view, 
    material_create_view,
    PaymentCreateView, PaymentListView,
    ClientCreateView, ClientDeleteView, ClientDetailView, ClientListView, ClientUpdateView,
    ProductCreateView,ProductListView, ProductDetailView, ProductUpdateView, ProductDeleteView,
    WorkerCreateView, WorkerListView, WorkerUpdateView, WorkerDetailView, WorkerDeleteView,
    OrderCreateView, OrderListView, OrderDetailView
    )

app_name = "pegado"
urlpatterns = [
    path('worker/', WorkerListView.as_view(), name="worker-list"),
    path('worker/<int:pk>/', WorkerDetailView.as_view(), name="worker-detail"),
    path('worker/<int:pk>/update', WorkerUpdateView.as_view(), name="worker-update"),
    path('worker/<int:pk>/delete', WorkerDeleteView.as_view(), name="worker-delete"),
    path('worker/create/', ProductCreateView.as_view(), name="worker-create"),
    path('product/', ProductListView.as_view(), name="product-list"),
    path('product/<int:pk>/', ProductDetailView.as_view(), name="product-detail"),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name="product-update"),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name="product-delete"),
    path('product/create/', ProductCreateView.as_view(), name="product-create"),
    path('client/', ClientListView.as_view(), name="client-list"),
    path('client/<int:pk>/', ClientDetailView.as_view(), name="client-detail"),
    path('client/<int:pk>/update', ClientUpdateView.as_view(), name="client-update"),
    path('client/<int:pk>/delete', ClientDeleteView.as_view(), name="client-delete"),
    path('client/create/', ClientCreateView.as_view(), name="client-create"),
    path('material/create/', material_create_view, name="material-create"),
    path('payment/create/', PaymentCreateView.as_view(), name="payment-create"),
    path('payment/', PaymentListView.as_view(), name="payment-list"),
    path('order/<int:pk>/', OrderDetailView.as_view(), name="order-detail"),
    path('order/create/', OrderCreateView.as_view(), name="order-create"),
    path('order/', OrderListView.as_view(), name="order-list")
    

]

Sistema/Troquelcart/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
	<title>Troquelcart</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="icon" type="icon" href= "{% static 'images/favicon.ico' %}">
    <meta name="description" content="Simple HTML5 Page layout template with header, footer, sidebar etc.">
</head>

<body>
	<header>
		<nav>  
			<ul>
				<li><a href= "{% url 'home' %}">Troquelcart</a>
				<li><a href="{% url 'pegado:worker-list' %}">Pegadoras</a>
				<li><a href="{% url 'pegado:product-list' %}">Productos</a>
				<li><a href="{% url 'pegado:client-list' %}">Clientes</a>
				<li><a href="{% url 'pegado:payment-list' %}">Pagos</a>
				<li><a href="{% url 'pegado:order-list' %}">Trabajos</a>
			</ul>
		</nav>
	</header>
	<section>
		{% block content %}
			<h1>Bienvenido a Troquelcart</h1>
			<h2>Página principal</h2>
		{% endblock %}
	</section>
	<section id="pageContent">
		<main >

		</main>

	</section>
	<footer>

	</footer>


</bo